---
- name: Install and configure Nextcloud on Debian
  hosts: all
  become: true
  become_method: sudo

  vars:
    nextcloud_version: "29.0.3"
    nextcloud_dir: /var/www/nextcloud
    nextcloud_data_dir: /srv/nextcloud-data
    db_name: nextcloud
    db_user: nextcloud
    db_password: "dskkfkfsr"          # put in Vault in real life
    admin_user: admin
    admin_password: "ChangeMeAdmin!"   # put in Vault in real life
    domain_name: "{{ ansible_default_ipv4.address }}"
    ansible_remote_tmp: /var/www/nextcloud/.ansible_tmp

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
          - mariadb-server
          - php
          - php-cli
          - php-mysql
          - php-zip
          - php-gd
          - php-curl
          - php-mbstring
          - php-intl
          - php-bcmath
          - php-gmp
          - php-xml
          - php-imagick
          - unzip
          - wget
        state: present
        
    - name: Ensure remote Ansible temp dir exists and is owned by www-data
      ansible.builtin.file:
        path: /var/www/nextcloud/.ansible_tmp
        state: directory
        owner: www-data
        group: www-data
        mode: "0700"
        
    - name: Ensure MariaDB is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    # -------- DB via CLI (no community collections) --------
    - name: Create database if missing (idempotent)
      ansible.builtin.shell: |
        set -euo pipefail
        if ! mysql -NBe "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='{{ db_name }}'" | grep -q .; then
          mysql -NBe "CREATE DATABASE \`{{ db_name }}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
          echo CHANGED
        fi
      args:
        executable: /bin/bash
      register: db_create
      changed_when: "'CHANGED' in db_create.stdout"

    - name: Ensure DB user exists and has privileges (idempotent)
      ansible.builtin.shell: |
        set -euo pipefail
        changed=0
        # Create user if needed
        if ! mysql -NBe "SELECT 1 FROM mysql.user WHERE user='{{ db_user }}' AND host='localhost'" | grep -q 1; then
          mysql -NBe "CREATE USER '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';"
          changed=1
        fi
        # Check grants and grant if missing
        if ! mysql -NBe "SHOW GRANTS FOR '{{ db_user }}'@'localhost'" | grep -q "ON \`{{ db_name }}\`\.\* TO '{{ db_user }}'@'localhost'"; then
          mysql -NBe "GRANT ALL PRIVILEGES ON \`{{ db_name }}\`.* TO '{{ db_user }}'@'localhost'; FLUSH PRIVILEGES;"
          changed=1
        fi
        if [ $changed -eq 1 ]; then echo CHANGED; fi
      args:
        executable: /bin/bash
      register: db_user_grant
      changed_when: "'CHANGED' in db_user_grant.stdout"
    # -------------------------------------------------------

    - name: Download Nextcloud tarball
      ansible.builtin.get_url:
        url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"
        dest: /tmp/nextcloud.tar.bz2
        mode: "0644"

    - name: Extract Nextcloud
      ansible.builtin.unarchive:
        src: /tmp/nextcloud.tar.bz2
        dest: /var/www/
        remote_src: true
        creates: "{{ nextcloud_dir }}/index.php"

    - name: Set permissions on Nextcloud directory
      ansible.builtin.file:
        path: "{{ nextcloud_dir }}"
        state: directory
        owner: www-data
        group: www-data
        recurse: true

    - name: Create data directory
      ansible.builtin.file:
        path: "{{ nextcloud_data_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0750"

    - name: Create Apache config for Nextcloud
      ansible.builtin.copy:
        dest: /etc/apache2/sites-available/nextcloud.conf
        mode: "0644"
        content: |
          <VirtualHost *:80>
            ServerName {{ domain_name }}

            DocumentRoot {{ nextcloud_dir }}
            <Directory {{ nextcloud_dir }}>
              Require all granted
              AllowOverride All
              Options FollowSymLinks MultiViews
            </Directory>
          </VirtualHost>
      notify: Reload Apache

    - name: Enable required Apache modules (idempotent-ish)
      ansible.builtin.shell: |
        a2enmod rewrite headers env dir mime
      args:
        executable: /bin/bash
      changed_when: false
      notify: Reload Apache

    - name: Enable Nextcloud site
      ansible.builtin.command: a2ensite nextcloud.conf
      args:
        creates: /etc/apache2/sites-enabled/nextcloud.conf
      notify: Reload Apache

    - name: Run Nextcloud installer (occ) if not already installed
      ansible.builtin.command: >
        php occ maintenance:install
        --database "mysql"
        --database-name "{{ db_name }}"
        --database-user "{{ db_user }}"
        --database-pass "{{ db_password }}"
        --admin-user "{{ admin_user }}"
        --admin-pass "{{ admin_password }}"
        --data-dir "{{ nextcloud_data_dir }}"
      args:
        chdir: "{{ nextcloud_dir }}"
        creates: "{{ nextcloud_dir }}/config/config.php"

    - name: Ensure trusted domain is set (idempotent)
      ansible.builtin.shell: |
        php occ config:system:get trusted_domains 1 >/dev/null 2>&1 || \
        php occ config:system:set trusted_domains 1 --value="{{ domain_name }}"
      args:
        chdir: "{{ nextcloud_dir }}"
        executable: /bin/bash
      become_user: www-data
      changed_when: false

  handlers:
    - name: Reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded
