---
- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: false

  vars:
    ospf_instance_name: core
    ospf_area_id: "0.0.0.0"
    ospf_version: "2" 
    
  tasks:

    - name: Check of OSPF instance al bestaat
      community.routeros.command:
        commands:
          - >
            /routing ospf instance
            :if ([:len [find where name="{{ ospf_instance_name }}"]] = 0) do={
              add name={{ ospf_instance_name }} router-id={{ router_id }} version={{ ospf_version }} redistribute=connected disabled=no
            } else={
              set [find where name="{{ ospf_instance_name }}"] router-id={{ router_id }} version={{ ospf_version }} redistribute=connected disabled=no
            }

    - name: Ensure backbone area exists
      community.routeros.command:
        commands:
          - >
            /routing ospf area
            :if ([:len [find where area-id={{ ospf_area_id }} && instance={{ ospf_instance_name }}]] = 0) do={
              add instance={{ ospf_instance_name }} area-id={{ ospf_area_id }}
            }

    - name: Ensure interface-templates for each network
      community.routeros.command:
        commands:
          - >
            /routing ospf interface-template
            :if ([:len [find where area={{ ospf_area_id }} && networks={{ item.network }}]] = 0) do={
              add area={{ ospf_area_id }} type={{ item.type }} networks={{ item.network }}
            }
      loop: "{{ ospf_networks }}"
      loop_control:
        label: "{{ item.network }} ({{ item.type }})"
