---
- name: RouterOS OSPF on 192.168.100.0/24 (network_cli)
  hosts: all
  gather_facts: false

  tasks:
    - name: Show OSPF neighbors (before)
      community.routeros.command:
        commands:
          - /routing ospf instance print
      register: ospf_neighbors_before

    - name: Debug OSPF neighbors (before)
      debug:
        var: ospf_neighbors_before.stdout_lines

    - name: Ensure OSPF instance "core" exists and is configured
      community.routeros.command:
        commands:
          - >
            :if ([:len [/routing ospf instance find where name="core"]] = 0) do={
              /routing ospf instance add name=core router-id={{ router_id }} version=2 redistribute=connected disabled=no
            } else={
              /routing ospf instance set [find where name="core"] router-id={{ router_id }} version=2 redistribute=connected disabled=no
            }
      register: ospf_instance_result

    - name: Ensure backbone area (0.0.0.0) exists on instance core
      community.routeros.command:
        commands:
          - >
            :if ([:len [/routing ospf area find where area-id=0.0.0.0 && instance=core]] = 0) do={
              /routing ospf area add instance=core area-id=0.0.0.0
            }
      register: ospf_area_result

    - name: Ensure interface-templates for each network (incl. 192.168.100.0/24)
      community.routeros.command:
        commands:
          - >
            :if ([:len [/routing ospf interface-template find where area=0.0.0.0 && networks="{{ item.network }}"]] = 0) do={
              /routing ospf interface-template add area=0.0.0.0 type={{ item.type }} networks={{ item.network }}
            }
      loop: "{{ ospf_networks }}"
      loop_control:
        label: "{{ item.network }} ({{ item.type }})"
      register: ospf_templates_result

    - name: Show template results (per item)
      debug:
        msg:
          network: "{{ item.item.network }}"
          type: "{{ item.item.type }}"
          stdout_lines: "{{ item.stdout_lines | default([]) }}"
      loop: "{{ ospf_templates_result.results }}"

    - name: Show OSPF neighbors (after)
      community.routeros.command:
        commands:
          - /routing ospf instance print
      register: ospf_neighbors_after

    - name: Debug OSPF neighbors (after)
      debug:
        var: ospf_neighbors_after.stdout_lines
