---
- name: Fallback without collections (raw SSH)
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh
  tasks:
    - name: Run resource print
      ansible.builtin.raw: /system resource print
      register: out

    - ansible.builtin.debug:
        var: out.stdout_lines
