---
- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: false

  tasks:

    - name: Check of OSPF instance al bestaat
      community.routeros.command:
        commands:
          - /routing ospf instance print detail where name=core
      register: system_resource_print

    - name: Maak OSPF instance (als die nog niet bestaat)
      community.routeros.command:
        commands:
          - /routing ospf instance add name=core router-id=0.0.0.0 version=2 redistribute=connected disabled=no
      when: inst_out.stdout[0] is not regex("name=core")

    - name: Update router-id indien nodig
      community.routeros.command:
        commands:
          - /routing ospf instance set [find where name=core] router-id=0.0.0.0 version=2 redistribute=connected disabled=no

    - name: Show system resources
      debug:
        var: system_resource_print.stdout_lines

    - name: Gather facts
      community.routeros.facts:

    - name: Show a fact
      debug:
        msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
  
