---
- name: Fallback without collections (raw SSH)
  hosts: all
  gather_facts: no
<<<<<<< HEAD
<<<<<<< HEAD
  vars:
    ansible_connection: ssh
=======
>>>>>>> parent of 26741f2 (Add community.network collection for OSPF configuration)
=======
>>>>>>> parent of 26741f2 (Add community.network collection for OSPF configuration)
  tasks:
    - name: Run resource print
      ansible.builtin.raw: /system resource print
      register: out

    - ansible.builtin.debug:
        var: out.stdout_lines
