---
- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: false

  tasks:
    - name: laat zien dat ospf er nog niet op staat
      community.routeros.command:
        commands:
          - /routing ospf neighbor print   
      register: OSPF_resource_print
    - name: Show system OSPF
      debug:
        var: OSPF_resource_print.stdout_lines
        
    - name: Check of OSPF instance al bestaat
      community.routeros.command:
        commands:
          - >
            /routing ospf instance
            :if ([:len [find where name="core"]] = 0) do={
              add name=core router-id= {{ router_id }} version=2 redistribute=connected disabled=no
            } else={
              set [find where name="core"] router-id={{ router_id }} version=2 redistribute=connected disabled=no
            }

    - name: Ensure backbone area exists
      community.routeros.command:
        commands:
          - >
            /routing ospf area
            :if ([:len [find where area-id=0.0.0.0 && instance=core]] = 0) do={
              add instance=core area-id=0.0.0.0
            }

    - name: Ensure interface-templates for each network
      community.routeros.command:
        commands:
          - >
            /routing ospf interface-template
            :if ([:len [find where area=0.0.0.0 && networks={{ item.network }}]] = 0) do={
              add area=0.0.0.0 type={{ item.type }} networks={{ item.network }}
            }
    - name: laat zien dat ospf nu werkt 
      community.routeros.command:
        command:
            /routing ospf neighbor print
      loop: "{{ ospf_networks }}"
      loop_control:
        label: "{{ item.network }} ({{ item.type }})"
